name: Commit Message Lint

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - edited
  workflow_dispatch:

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint commit messages (Conventional Commits)
        uses: wagoid/commitlint-github-action@v6
        with:
          failOnWarnings: true
          configFile: .commitlintrc.json
